name: "job_market_dbt"
version: "1.0.0"
config-version: 2

profile: "job_market_dbt"

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  job_market_dbt:
    staging:
      +schema: staging
      +materialized: view

    intermediate:
      +schema: intermediate
      +materialized: view

    marts:
      +schema: marts
      +materialized: table

seeds:
  job_market_dbt:
    +schema: reference

    referentiel_departements:
      +column_types:
        code_departement: varchar(3)
        nom_departement: varchar(200)
        code_region: varchar(2)
        nom_region: varchar(200)
